/*
 * Hecho con <3 por GarciHard xD n_n *-* :D
 */

package vistaSAV;

/**
 *
 * @author Hecho con <3 por GarciHard xD n_n *-* :D
 */
public class EmpleadoSAV extends javax.swing.JFrame {

    /**
     * Creates new form EmpleadoSAV
     */
    public EmpleadoSAV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEmpleadoBackground = new javax.swing.JPanel();
        panelEmpleadoGral = new javax.swing.JPanel();
        btnEmpleadoVuelos = new javax.swing.JButton();
        btnEmpleadoSalir = new javax.swing.JButton();
        btnEmpleadoCambiarUsuario = new javax.swing.JButton();
        btnEmpleadoOrdenes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEmpleadoBackground.setBackground(new java.awt.Color(158, 158, 158));

        javax.swing.GroupLayout panelEmpleadoGralLayout = new javax.swing.GroupLayout(panelEmpleadoGral);
        panelEmpleadoGral.setLayout(panelEmpleadoGralLayout);
        panelEmpleadoGralLayout.setHorizontalGroup(
            panelEmpleadoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        panelEmpleadoGralLayout.setVerticalGroup(
            panelEmpleadoGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        btnEmpleadoVuelos.setBackground(new java.awt.Color(52, 152, 219));
        btnEmpleadoVuelos.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N
        btnEmpleadoVuelos.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleadoVuelos.setText("Vuelos");
        btnEmpleadoVuelos.setBorder(null);
        btnEmpleadoVuelos.setBorderPainted(false);
        btnEmpleadoVuelos.setContentAreaFilled(false);
        btnEmpleadoVuelos.setOpaque(true);

        btnEmpleadoSalir.setBackground(new java.awt.Color(211, 84, 0));
        btnEmpleadoSalir.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N
        btnEmpleadoSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleadoSalir.setText("Salir");
        btnEmpleadoSalir.setBorder(null);
        btnEmpleadoSalir.setBorderPainted(false);
        btnEmpleadoSalir.setContentAreaFilled(false);
        btnEmpleadoSalir.setOpaque(true);

        btnEmpleadoCambiarUsuario.setBackground(new java.awt.Color(52, 73, 94));
        btnEmpleadoCambiarUsuario.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpleadoCambiarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleadoCambiarUsuario.setText("<html><p align= center>Cambiar<br>Usuario</html>");
        btnEmpleadoCambiarUsuario.setBorder(null);
        btnEmpleadoCambiarUsuario.setBorderPainted(false);
        btnEmpleadoCambiarUsuario.setContentAreaFilled(false);
        btnEmpleadoCambiarUsuario.setOpaque(true);

        btnEmpleadoOrdenes.setBackground(new java.awt.Color(243, 156, 18));
        btnEmpleadoOrdenes.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N
        btnEmpleadoOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpleadoOrdenes.setText("Ordenes");
        btnEmpleadoOrdenes.setToolTipText("");
        btnEmpleadoOrdenes.setBorder(null);
        btnEmpleadoOrdenes.setBorderPainted(false);
        btnEmpleadoOrdenes.setContentAreaFilled(false);
        btnEmpleadoOrdenes.setOpaque(true);

        javax.swing.GroupLayout panelEmpleadoBackgroundLayout = new javax.swing.GroupLayout(panelEmpleadoBackground);
        panelEmpleadoBackground.setLayout(panelEmpleadoBackgroundLayout);
        panelEmpleadoBackgroundLayout.setHorizontalGroup(
            panelEmpleadoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadoBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmpleadoCambiarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(btnEmpleadoSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmpleadoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEmpleadoGral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEmpleadoBackgroundLayout.createSequentialGroup()
                        .addComponent(btnEmpleadoVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmpleadoOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panelEmpleadoBackgroundLayout.setVerticalGroup(
            panelEmpleadoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadoBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadoBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmpleadoVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEmpleadoBackgroundLayout.createSequentialGroup()
                        .addComponent(btnEmpleadoOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addComponent(panelEmpleadoGral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadoBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEmpleadoCambiarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmpleadoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEmpleadoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEmpleadoBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadoSAV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadoSAV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadoSAV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadoSAV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadoSAV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEmpleadoCambiarUsuario;
    public javax.swing.JButton btnEmpleadoOrdenes;
    public javax.swing.JButton btnEmpleadoSalir;
    public javax.swing.JButton btnEmpleadoVuelos;
    public javax.swing.JPanel panelEmpleadoBackground;
    public javax.swing.JPanel panelEmpleadoGral;
    // End of variables declaration//GEN-END:variables
}
