package vistaSAV;
//@author GarciHard
import controladorSAV.LoginControlador;
import modeloSAV.SAVUsuariosDAO;


public class LoginCTV extends javax.swing.JFrame {
 
    /*Constructor del JFrame LoginCTV*/
    public LoginCTV() {
        //this.setExtendedState(LoginCTV.MAXIMIZED_BOTH);/*tamaño de inicio del tamaño de la ventana*/
        //this.setUndecorated(false); /*quitamos el marco de la ventana que tiene los botonos max,min,cls*/
        //this.setOpacity(0.8f);//hacer transparente la ventana pero solo funciona con el Undecorated
        //this.setLocationRelativeTo(null);//para centrar la ventana
        //this.setLocation(275, 100);//una posicion personalizada .-.
         initComponents();
    }
    /*Fin Constructor*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginBackground = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnAcceso = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        menuLogin = new javax.swing.JMenuBar();
        menuCTV = new javax.swing.JMenu();
        menuAcercade = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuAyudaLogin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("C T V .:. v0.3");
        setResizable(false);

        panelLoginBackground.setBackground(new java.awt.Color(52, 152, 219));

        lblLogo.setBackground(new java.awt.Color(51, 204, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSAV/AppSinFondo_opt.png"))); // NOI18N
        lblLogo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(52, 152, 219), new java.awt.Color(52, 73, 94)));

        lblUsuario.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");

        lblContraseña.setFont(new java.awt.Font("Heiti SC", 0, 20)); // NOI18N
        lblContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContraseña.setText("Contraseña");

        btnAcceso.setBackground(new java.awt.Color(211, 84, 0));
        btnAcceso.setFont(new java.awt.Font("Courier", 0, 14)); // NOI18N
        btnAcceso.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceso.setText("Login");
        btnAcceso.setToolTipText("Iniciar Sesión en el Sistema Administrativo de Vuelos EOLO");
        btnAcceso.setBorder(null);
        btnAcceso.setBorderPainted(false);
        btnAcceso.setContentAreaFilled(false);
        btnAcceso.setFocusPainted(false);
        btnAcceso.setOpaque(true);

        txtUsuario.setFont(new java.awt.Font("Heiti SC", 0, 16)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtContraseña.setFont(new java.awt.Font("Heiti SC", 1, 16)); // NOI18N
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblContraseña, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblUsuario)
                .addGap(19, 19, 19)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblContraseña)
                .addGap(19, 19, 19)
                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelLoginBackgroundLayout = new javax.swing.GroupLayout(panelLoginBackground);
        panelLoginBackground.setLayout(panelLoginBackgroundLayout);
        panelLoginBackgroundLayout.setHorizontalGroup(
            panelLoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginBackgroundLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(panelLoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );
        panelLoginBackgroundLayout.setVerticalGroup(
            panelLoginBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginBackgroundLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        menuLogin.setBackground(new java.awt.Color(51, 204, 255));
        menuLogin.setBorder(null);

        menuCTV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuCTV.setText("  S.A.V  .:. v0.3   ");

        menuAcercade.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        menuAcercade.setText("Acerca de");
        menuCTV.add(menuAcercade);
        menuCTV.add(jSeparator1);

        menuSalir.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        menuSalir.setText("Salir");
        menuCTV.add(menuSalir);

        menuLogin.add(menuCTV);

        menuAyuda.setText("   Ayuda   ");

        menuAyudaLogin.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        menuAyudaLogin.setText("Ayuda Login");
        menuAyuda.add(menuAyudaLogin);

        menuLogin.add(menuAyuda);

        setJMenuBar(menuLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLoginBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLoginBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCTV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        LoginCTV logFrame = new LoginCTV();
        SAVUsuariosDAO user = new SAVUsuariosDAO();
        LoginControlador login = new LoginControlador(logFrame, user);
        login.inicializarLogin();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAcceso;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblUsuario;
    public javax.swing.JMenuItem menuAcercade;
    private javax.swing.JMenu menuAyuda;
    public javax.swing.JMenuItem menuAyudaLogin;
    private javax.swing.JMenu menuCTV;
    private javax.swing.JMenuBar menuLogin;
    public javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelLoginBackground;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
