/*
 * Hecho con <3 por GarciHard xD n_n *-* :D
 */

package vistaSAV;

/**
 *
 * @author Hecho con <3 por GarciHard xD n_n *-* :D
 */
public class PanelReservacionesEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelReservacionesEmpleado
     */
    public PanelReservacionesEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnResEmpListarPasajeros = new javax.swing.JButton();
        lblEmpAdminFechaNacimiento = new javax.swing.JLabel();
        btnResEmpModificarPas = new javax.swing.JButton();
        lblEmpAdminApellidoPaterno = new javax.swing.JLabel();
        lblEmpAdminApellidoMaterno = new javax.swing.JLabel();
        txtResEmpApellidoPaternoPas = new javax.swing.JTextField();
        lblEmpAdminNombre = new javax.swing.JLabel();
        txtResEmpApellidoMaternoPas = new javax.swing.JTextField();
        lblResEmpHeaderDatosPersonales = new javax.swing.JLabel();
        lblEmpAdmHeaderDatosPersonalesSeparador = new javax.swing.JLabel();
        txtResEmpTelefonoPas = new javax.swing.JTextField();
        txtResEmpEMailPas = new javax.swing.JTextField();
        txtResEmpEmpresaPas = new javax.swing.JTextField();
        comboResEmpTipoVueloPas = new javax.swing.JComboBox();
        txtResEmpCaducidadPasaportePas = new com.toedter.calendar.JDateChooser();
        btnResEmpCancelarPas = new javax.swing.JButton();
        lblEmpAdminBuscarEmp = new javax.swing.JLabel();
        lblEmpAdminHeaderListadoPersonal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpAdminListadoPersonal = new javax.swing.JTable();
        lblEmpAdmHeaderListadoPersonalSeparador = new javax.swing.JLabel();
        lblEmpAdminTelefono = new javax.swing.JLabel();
        lblEmpAdminEMail = new javax.swing.JLabel();
        lblEmpAdminHeaderDatosUsuario = new javax.swing.JLabel();
        lblEmpAdmHeaderDatosUsuarioSeparador = new javax.swing.JLabel();
        lblEmpAdminCargo = new javax.swing.JLabel();
        lblEmpAdminUsuario = new javax.swing.JLabel();
        txtResEmpNombrePas = new javax.swing.JTextField();
        btnResEmpBuscarPas = new javax.swing.JButton();
        btnResEmpEliminarPas = new javax.swing.JButton();
        btnResEmpNuevoPasajero = new javax.swing.JButton();
        btnResEmpGuardarPas = new javax.swing.JButton();
        txtResEmpBuscarPas = new javax.swing.JTextField();
        lblEmpAdminApellidoMaterno1 = new javax.swing.JLabel();
        txtResEmpNoPasaporte = new javax.swing.JTextField();
        txtResEmpNoPasajerosPas = new javax.swing.JTextField();
        lblEmpAdminEMail1 = new javax.swing.JLabel();
        txtResEmpRutaPas = new javax.swing.JTextField();
        lblEmpAdminEMail2 = new javax.swing.JLabel();
        comboResEmpTipoPagoPas = new javax.swing.JComboBox();
        lblEmpAdminCargo1 = new javax.swing.JLabel();
        lblEmpAdminEMail3 = new javax.swing.JLabel();
        txtResEmpFechaVueloPas = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(52, 152, 219));

        btnResEmpListarPasajeros.setBackground(new java.awt.Color(0, 100, 133));
        btnResEmpListarPasajeros.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpListarPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        btnResEmpListarPasajeros.setText("Listar Clientes");
        btnResEmpListarPasajeros.setBorderPainted(false);
        btnResEmpListarPasajeros.setContentAreaFilled(false);
        btnResEmpListarPasajeros.setOpaque(true);

        lblEmpAdminFechaNacimiento.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminFechaNacimiento.setText("Fecha Caducidad");

        btnResEmpModificarPas.setBackground(new java.awt.Color(0, 100, 133));
        btnResEmpModificarPas.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpModificarPas.setForeground(new java.awt.Color(255, 255, 255));
        btnResEmpModificarPas.setText("Modificar");
        btnResEmpModificarPas.setBorder(null);
        btnResEmpModificarPas.setBorderPainted(false);
        btnResEmpModificarPas.setContentAreaFilled(false);
        btnResEmpModificarPas.setOpaque(true);

        lblEmpAdminApellidoPaterno.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoPaterno.setText("Apellido Paterno");

        lblEmpAdminApellidoMaterno.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoMaterno.setText("Apellido Materno");

        lblEmpAdminNombre.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminNombre.setText("Nombre(s)");

        lblResEmpHeaderDatosPersonales.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblResEmpHeaderDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        lblResEmpHeaderDatosPersonales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResEmpHeaderDatosPersonales.setText("Datos Pasajero");

        lblEmpAdmHeaderDatosPersonalesSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderDatosPersonalesSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderDatosPersonalesSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderDatosPersonalesSeparador.setText("______________________________________________________________________________");
        lblEmpAdmHeaderDatosPersonalesSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        comboResEmpTipoVueloPas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione una opción>", "Administrador", "Empleado Tráfico" }));

        txtResEmpCaducidadPasaportePas.setBackground(new java.awt.Color(52, 152, 219));
        txtResEmpCaducidadPasaportePas.setDateFormatString("dd/MM/yyyy");

        btnResEmpCancelarPas.setBackground(new java.awt.Color(52, 152, 219));
        btnResEmpCancelarPas.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpCancelarPas.setForeground(new java.awt.Color(52, 152, 219));
        btnResEmpCancelarPas.setText("Cancelar");
        btnResEmpCancelarPas.setBorderPainted(false);
        btnResEmpCancelarPas.setContentAreaFilled(false);
        btnResEmpCancelarPas.setOpaque(true);

        lblEmpAdminBuscarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminBuscarEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminBuscarEmp.setText("Buscar");

        lblEmpAdminHeaderListadoPersonal.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderListadoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderListadoPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminHeaderListadoPersonal.setText("Clientes Frecuentes");

        tablaEmpAdminListadoPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpAdminListadoPersonal);

        lblEmpAdmHeaderListadoPersonalSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderListadoPersonalSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderListadoPersonalSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderListadoPersonalSeparador.setText("____________________________________________________________________________");
        lblEmpAdmHeaderListadoPersonalSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblEmpAdminTelefono.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminTelefono.setText("Teléfono");

        lblEmpAdminEMail.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminEMail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminEMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminEMail.setText("E-mail");

        lblEmpAdminHeaderDatosUsuario.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderDatosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderDatosUsuario.setText("Datos Vuelo");

        lblEmpAdmHeaderDatosUsuarioSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderDatosUsuarioSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderDatosUsuarioSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderDatosUsuarioSeparador.setText("________________________________________________________________________________");
        lblEmpAdmHeaderDatosUsuarioSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblEmpAdminCargo.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminCargo.setText("Tipo de Vuelo");

        lblEmpAdminUsuario.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminUsuario.setText("Empresa");

        btnResEmpBuscarPas.setBackground(new java.awt.Color(0, 100, 133));
        btnResEmpBuscarPas.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpBuscarPas.setForeground(new java.awt.Color(255, 255, 255));
        btnResEmpBuscarPas.setText("Buscar");
        btnResEmpBuscarPas.setBorderPainted(false);
        btnResEmpBuscarPas.setContentAreaFilled(false);
        btnResEmpBuscarPas.setOpaque(true);

        btnResEmpEliminarPas.setBackground(new java.awt.Color(0, 100, 133));
        btnResEmpEliminarPas.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpEliminarPas.setForeground(new java.awt.Color(255, 255, 255));
        btnResEmpEliminarPas.setText("Eliminar");
        btnResEmpEliminarPas.setBorder(null);
        btnResEmpEliminarPas.setBorderPainted(false);
        btnResEmpEliminarPas.setContentAreaFilled(false);
        btnResEmpEliminarPas.setOpaque(true);

        btnResEmpNuevoPasajero.setBackground(new java.awt.Color(0, 100, 133));
        btnResEmpNuevoPasajero.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpNuevoPasajero.setForeground(new java.awt.Color(255, 255, 255));
        btnResEmpNuevoPasajero.setText("Nuevo");
        btnResEmpNuevoPasajero.setBorder(null);
        btnResEmpNuevoPasajero.setBorderPainted(false);
        btnResEmpNuevoPasajero.setContentAreaFilled(false);
        btnResEmpNuevoPasajero.setOpaque(true);

        btnResEmpGuardarPas.setBackground(new java.awt.Color(0, 100, 133));
        btnResEmpGuardarPas.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnResEmpGuardarPas.setForeground(new java.awt.Color(255, 255, 255));
        btnResEmpGuardarPas.setText("Guardar");
        btnResEmpGuardarPas.setBorder(null);
        btnResEmpGuardarPas.setBorderPainted(false);
        btnResEmpGuardarPas.setContentAreaFilled(false);
        btnResEmpGuardarPas.setOpaque(true);

        lblEmpAdminApellidoMaterno1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoMaterno1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoMaterno1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoMaterno1.setText("No. Pasaporte");

        lblEmpAdminEMail1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminEMail1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminEMail1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminEMail1.setText("No. Pasajeros");

        lblEmpAdminEMail2.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminEMail2.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminEMail2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminEMail2.setText("Ruta");

        comboResEmpTipoPagoPas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione una opción>", "Administrador", "Empleado Tráfico" }));

        lblEmpAdminCargo1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminCargo1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminCargo1.setText("Tipo de Pago");

        lblEmpAdminEMail3.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminEMail3.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminEMail3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminEMail3.setText("Fecha Vuelo");

        txtResEmpFechaVueloPas.setBackground(new java.awt.Color(52, 152, 219));
        txtResEmpFechaVueloPas.setDateFormatString("dd/MM/yyyy");

        jButton1.setBackground(new java.awt.Color(0, 100, 133));
        jButton1.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Abv. Rutas");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmpAdmHeaderDatosUsuarioSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblEmpAdminHeaderDatosUsuario))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmpAdminTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtResEmpTelefonoPas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmpAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEmpAdminApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEmpAdminApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblEmpAdminFechaNacimiento)
                                            .addComponent(lblEmpAdminApellidoMaterno1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtResEmpNombrePas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResEmpApellidoPaternoPas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResEmpApellidoMaternoPas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResEmpCaducidadPasaportePas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResEmpNoPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmpAdminEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtResEmpEMailPas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEmpAdminEMail3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminEMail2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboResEmpTipoPagoPas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtResEmpEmpresaPas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(comboResEmpTipoVueloPas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtResEmpRutaPas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtResEmpFechaVueloPas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(88, 88, 88)
                                                        .addComponent(lblEmpAdminEMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtResEmpNoPasajerosPas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnResEmpNuevoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResEmpGuardarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResEmpModificarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResEmpEliminarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResEmpCancelarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmpAdminBuscarEmp)
                                .addGap(6, 6, 6)
                                .addComponent(txtResEmpBuscarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnResEmpBuscarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResEmpListarPasajeros))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblEmpAdmHeaderDatosPersonalesSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblResEmpHeaderDatosPersonales)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpAdminHeaderListadoPersonal)
                            .addComponent(lblEmpAdmHeaderListadoPersonalSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResEmpHeaderDatosPersonales)
                    .addComponent(lblEmpAdminHeaderListadoPersonal))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpAdmHeaderDatosPersonalesSeparador)
                    .addComponent(lblEmpAdmHeaderListadoPersonalSeparador))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblEmpAdminBuscarEmp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtResEmpBuscarPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnResEmpBuscarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResEmpListarPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnResEmpGuardarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnResEmpNuevoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnResEmpEliminarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnResEmpModificarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnResEmpCancelarPas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminNombre)
                                .addGap(25, 25, 25)
                                .addComponent(lblEmpAdminApellidoPaterno)
                                .addGap(25, 25, 25)
                                .addComponent(lblEmpAdminApellidoMaterno)
                                .addGap(25, 25, 25)
                                .addComponent(lblEmpAdminApellidoMaterno1)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmpAdminFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtResEmpNombrePas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtResEmpApellidoPaternoPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtResEmpApellidoMaternoPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtResEmpNoPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtResEmpCaducidadPasaportePas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminTelefono))
                            .addComponent(txtResEmpTelefonoPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminEMail))
                            .addComponent(txtResEmpEMailPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblEmpAdminHeaderDatosUsuario)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmpAdmHeaderDatosUsuarioSeparador)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtResEmpFechaVueloPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminEMail3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmpAdminEMail1)
                                .addComponent(txtResEmpNoPasajerosPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminEMail2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtResEmpRutaPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboResEmpTipoVueloPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResEmpEmpresaPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminUsuario))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboResEmpTipoPagoPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminCargo1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnResEmpBuscarPas;
    public javax.swing.JButton btnResEmpCancelarPas;
    public javax.swing.JButton btnResEmpEliminarPas;
    public javax.swing.JButton btnResEmpGuardarPas;
    public javax.swing.JButton btnResEmpListarPasajeros;
    public javax.swing.JButton btnResEmpModificarPas;
    public javax.swing.JButton btnResEmpNuevoPasajero;
    public javax.swing.JComboBox comboResEmpTipoPagoPas;
    public javax.swing.JComboBox comboResEmpTipoVueloPas;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpAdmHeaderDatosPersonalesSeparador;
    private javax.swing.JLabel lblEmpAdmHeaderDatosUsuarioSeparador;
    private javax.swing.JLabel lblEmpAdmHeaderListadoPersonalSeparador;
    private javax.swing.JLabel lblEmpAdminApellidoMaterno;
    private javax.swing.JLabel lblEmpAdminApellidoMaterno1;
    private javax.swing.JLabel lblEmpAdminApellidoPaterno;
    private javax.swing.JLabel lblEmpAdminBuscarEmp;
    private javax.swing.JLabel lblEmpAdminCargo;
    private javax.swing.JLabel lblEmpAdminCargo1;
    private javax.swing.JLabel lblEmpAdminEMail;
    private javax.swing.JLabel lblEmpAdminEMail1;
    private javax.swing.JLabel lblEmpAdminEMail2;
    private javax.swing.JLabel lblEmpAdminEMail3;
    private javax.swing.JLabel lblEmpAdminFechaNacimiento;
    private javax.swing.JLabel lblEmpAdminHeaderDatosUsuario;
    private javax.swing.JLabel lblEmpAdminHeaderListadoPersonal;
    private javax.swing.JLabel lblEmpAdminNombre;
    private javax.swing.JLabel lblEmpAdminTelefono;
    private javax.swing.JLabel lblEmpAdminUsuario;
    private javax.swing.JLabel lblResEmpHeaderDatosPersonales;
    public javax.swing.JTable tablaEmpAdminListadoPersonal;
    public javax.swing.JTextField txtResEmpApellidoMaternoPas;
    public javax.swing.JTextField txtResEmpApellidoPaternoPas;
    public javax.swing.JTextField txtResEmpBuscarPas;
    public com.toedter.calendar.JDateChooser txtResEmpCaducidadPasaportePas;
    public javax.swing.JTextField txtResEmpEMailPas;
    public javax.swing.JTextField txtResEmpEmpresaPas;
    public com.toedter.calendar.JDateChooser txtResEmpFechaVueloPas;
    public javax.swing.JTextField txtResEmpNoPasajerosPas;
    public javax.swing.JTextField txtResEmpNoPasaporte;
    public javax.swing.JTextField txtResEmpNombrePas;
    public javax.swing.JTextField txtResEmpRutaPas;
    public javax.swing.JTextField txtResEmpTelefonoPas;
    // End of variables declaration//GEN-END:variables
}
