/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistaSAV;

/**
 *
 * @author GarciHard
 */
public class PanelEmpleadoAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelEmpleadoAdmin
     */
    public PanelEmpleadoAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbgSexo = new javax.swing.ButtonGroup();
        lblEmpAdminHeaderDatosPersonales = new javax.swing.JLabel();
        lblEmpAdmHeaderDatosPersonalesSeparador = new javax.swing.JLabel();
        btnEmpAdminFoto = new javax.swing.JButton();
        lblEmpAdminNombre = new javax.swing.JLabel();
        lblEmpAdminApellidoPaterno = new javax.swing.JLabel();
        lblEmpAdminApellidoMaterno = new javax.swing.JLabel();
        lblEmpAdminFechaNacimiento = new javax.swing.JLabel();
        lblEmpAdminRFC = new javax.swing.JLabel();
        lblEmpAdminSexo = new javax.swing.JLabel();
        lblEmpAdminDomicilio = new javax.swing.JLabel();
        lblEmpAdminTelefono = new javax.swing.JLabel();
        lblEmpAdminEMail = new javax.swing.JLabel();
        lblEmpAdminNivelEstudios = new javax.swing.JLabel();
        lblEmpAdminHeaderDatosUsuario = new javax.swing.JLabel();
        lblEmpAdmHeaderDatosUsuarioSeparador = new javax.swing.JLabel();
        lblEmpAdminCargo = new javax.swing.JLabel();
        lblEmpAdminHorario = new javax.swing.JLabel();
        lblEmpAdminUsuario = new javax.swing.JLabel();
        lblEmpAdminContraseña = new javax.swing.JLabel();
        txtEmpAdminNombre = new javax.swing.JTextField();
        txtEmpAdminApellidoPaterno = new javax.swing.JTextField();
        txtEmpAdminApellidoMaterno = new javax.swing.JTextField();
        txtEmpAdminRFC = new javax.swing.JTextField();
        txtEmpAdminDomicilio = new javax.swing.JTextField();
        txtEmpAdminTelefono = new javax.swing.JTextField();
        txtEmpAdminEMail = new javax.swing.JTextField();
        txtEmpAdminNivelEstudios = new javax.swing.JTextField();
        txtEmpAdminFechaNacimiento = new com.toedter.calendar.JDateChooser();
        comboEmpAdminCargo = new javax.swing.JComboBox();
        comboEmpAdminHorario = new javax.swing.JComboBox();
        txtEmpAdminUsuario = new javax.swing.JTextField();
        txtEmpAdminContraseña = new javax.swing.JPasswordField();
        lblEmpAdminHeaderListadoPersonal = new javax.swing.JLabel();
        lblEmpAdmHeaderListadoPersonalSeparador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpAdminListadoPersonal = new javax.swing.JTable();
        lblEmpAdminBuscarEmp = new javax.swing.JLabel();
        txtEmpAdminBuscarEmp = new javax.swing.JTextField();
        btnEmpAdminBuscarEmp = new javax.swing.JButton();
        btnEmpAdminEliminarEmp = new javax.swing.JButton();
        btnEmpAdminNuevoEmp = new javax.swing.JButton();
        btnEmpAdminGuardarEmp = new javax.swing.JButton();
        btnEmpAdminModificarEmp = new javax.swing.JButton();
        lblEmpAdminNumeroEmpleado = new javax.swing.JLabel();
        rbtFemenino = new javax.swing.JRadioButton();
        rbtMasculino = new javax.swing.JRadioButton();
        btnEmpAdminListarEmpleados = new javax.swing.JButton();
        btnEmpAdminCancelar = new javax.swing.JButton();
        txtEmpAdminNumeroEmpleado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(26, 188, 156));

        lblEmpAdminHeaderDatosPersonales.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderDatosPersonales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminHeaderDatosPersonales.setText("Datos Personales");

        lblEmpAdmHeaderDatosPersonalesSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderDatosPersonalesSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderDatosPersonalesSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderDatosPersonalesSeparador.setText("______________________________________________________________________________");
        lblEmpAdmHeaderDatosPersonalesSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnEmpAdminFoto.setBackground(new java.awt.Color(26, 188, 156));
        btnEmpAdminFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSAV/ImagenNoDisponibleII.png"))); // NOI18N
        btnEmpAdminFoto.setBorderPainted(false);
        btnEmpAdminFoto.setContentAreaFilled(false);
        btnEmpAdminFoto.setOpaque(true);

        lblEmpAdminNombre.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminNombre.setText("Nombre(s)");

        lblEmpAdminApellidoPaterno.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoPaterno.setText("Apellido Paterno");

        lblEmpAdminApellidoMaterno.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoMaterno.setText("Apellido Materno");

        lblEmpAdminFechaNacimiento.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminFechaNacimiento.setText("Fecha Nacimiento");

        lblEmpAdminRFC.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminRFC.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminRFC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminRFC.setText("R.F.C");

        lblEmpAdminSexo.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminSexo.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminSexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminSexo.setText("Sexo");

        lblEmpAdminDomicilio.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminDomicilio.setText("Domicilio");

        lblEmpAdminTelefono.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminTelefono.setText("Teléfono");

        lblEmpAdminEMail.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminEMail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminEMail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminEMail.setText("E-mail");

        lblEmpAdminNivelEstudios.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminNivelEstudios.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminNivelEstudios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminNivelEstudios.setText("Nivel de Estudios");

        lblEmpAdminHeaderDatosUsuario.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderDatosUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderDatosUsuario.setText("Datos Usuario");

        lblEmpAdmHeaderDatosUsuarioSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderDatosUsuarioSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderDatosUsuarioSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderDatosUsuarioSeparador.setText("________________________________________________________________________________");
        lblEmpAdmHeaderDatosUsuarioSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblEmpAdminCargo.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminCargo.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminCargo.setText("Cargo");

        lblEmpAdminHorario.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminHorario.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHorario.setText("Horario");

        lblEmpAdminUsuario.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminUsuario.setText("Usuario");

        lblEmpAdminContraseña.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminContraseña.setText("Contraseña");

        txtEmpAdminDomicilio.setColumns(1);
        txtEmpAdminDomicilio.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtEmpAdminNivelEstudios.setColumns(1);
        txtEmpAdminNivelEstudios.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txtEmpAdminFechaNacimiento.setBackground(new java.awt.Color(26, 188, 156));
        txtEmpAdminFechaNacimiento.setDateFormatString("dd/MM/yyyy");

        comboEmpAdminCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione una opción>", "Administrador", "Empleado Tráfico" }));

        comboEmpAdminHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione una opción>", "Matutino 7:00 - 15:00", "Vespertino 15:00 - 23:00" }));

        lblEmpAdminHeaderListadoPersonal.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderListadoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderListadoPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminHeaderListadoPersonal.setText("Personal Actual");

        lblEmpAdmHeaderListadoPersonalSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderListadoPersonalSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderListadoPersonalSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderListadoPersonalSeparador.setText("____________________________________________________________________________");
        lblEmpAdmHeaderListadoPersonalSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tablaEmpAdminListadoPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEmpAdminListadoPersonal);

        lblEmpAdminBuscarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminBuscarEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminBuscarEmp.setText("Buscar");

        btnEmpAdminBuscarEmp.setBackground(new java.awt.Color(0, 100, 133));
        btnEmpAdminBuscarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminBuscarEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpAdminBuscarEmp.setText("Buscar");
        btnEmpAdminBuscarEmp.setBorderPainted(false);
        btnEmpAdminBuscarEmp.setContentAreaFilled(false);
        btnEmpAdminBuscarEmp.setOpaque(true);

        btnEmpAdminEliminarEmp.setBackground(new java.awt.Color(0, 100, 133));
        btnEmpAdminEliminarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminEliminarEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpAdminEliminarEmp.setText("Eliminar");
        btnEmpAdminEliminarEmp.setBorder(null);
        btnEmpAdminEliminarEmp.setBorderPainted(false);
        btnEmpAdminEliminarEmp.setContentAreaFilled(false);
        btnEmpAdminEliminarEmp.setOpaque(true);

        btnEmpAdminNuevoEmp.setBackground(new java.awt.Color(0, 100, 133));
        btnEmpAdminNuevoEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminNuevoEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpAdminNuevoEmp.setText("Nuevo");
        btnEmpAdminNuevoEmp.setBorder(null);
        btnEmpAdminNuevoEmp.setBorderPainted(false);
        btnEmpAdminNuevoEmp.setContentAreaFilled(false);
        btnEmpAdminNuevoEmp.setOpaque(true);

        btnEmpAdminGuardarEmp.setBackground(new java.awt.Color(0, 100, 133));
        btnEmpAdminGuardarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminGuardarEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpAdminGuardarEmp.setText("Guardar");
        btnEmpAdminGuardarEmp.setBorder(null);
        btnEmpAdminGuardarEmp.setBorderPainted(false);
        btnEmpAdminGuardarEmp.setContentAreaFilled(false);
        btnEmpAdminGuardarEmp.setOpaque(true);

        btnEmpAdminModificarEmp.setBackground(new java.awt.Color(0, 100, 133));
        btnEmpAdminModificarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminModificarEmp.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpAdminModificarEmp.setText("Modificar");
        btnEmpAdminModificarEmp.setBorder(null);
        btnEmpAdminModificarEmp.setBorderPainted(false);
        btnEmpAdminModificarEmp.setContentAreaFilled(false);
        btnEmpAdminModificarEmp.setOpaque(true);

        lblEmpAdminNumeroEmpleado.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminNumeroEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminNumeroEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminNumeroEmpleado.setText("Número de Empleado");

        rbgSexo.add(rbtFemenino);
        rbtFemenino.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        rbtFemenino.setForeground(new java.awt.Color(255, 255, 255));
        rbtFemenino.setText("Femenino");

        rbgSexo.add(rbtMasculino);
        rbtMasculino.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        rbtMasculino.setForeground(new java.awt.Color(255, 255, 255));
        rbtMasculino.setText("Masculino");

        btnEmpAdminListarEmpleados.setBackground(new java.awt.Color(0, 100, 133));
        btnEmpAdminListarEmpleados.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminListarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpAdminListarEmpleados.setText("Listar Empleados");
        btnEmpAdminListarEmpleados.setBorderPainted(false);
        btnEmpAdminListarEmpleados.setContentAreaFilled(false);
        btnEmpAdminListarEmpleados.setOpaque(true);

        btnEmpAdminCancelar.setBackground(new java.awt.Color(26, 188, 156));
        btnEmpAdminCancelar.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnEmpAdminCancelar.setForeground(new java.awt.Color(26, 188, 156));
        btnEmpAdminCancelar.setText("Cancelar");
        btnEmpAdminCancelar.setBorderPainted(false);
        btnEmpAdminCancelar.setContentAreaFilled(false);
        btnEmpAdminCancelar.setOpaque(true);

        txtEmpAdminNumeroEmpleado.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        txtEmpAdminNumeroEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        txtEmpAdminNumeroEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblEmpAdminHeaderDatosPersonales)
                        .addGap(338, 338, 338)
                        .addComponent(lblEmpAdminHeaderListadoPersonal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblEmpAdmHeaderDatosPersonalesSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmpAdmHeaderListadoPersonalSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(lblEmpAdminSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(rbtFemenino)
                                        .addGap(12, 12, 12)
                                        .addComponent(rbtMasculino))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(lblEmpAdminTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtEmpAdminTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(lblEmpAdminEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtEmpAdminEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(lblEmpAdminNivelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtEmpAdminNivelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblEmpAdminHeaderDatosUsuario))
                                    .addComponent(lblEmpAdmHeaderDatosUsuarioSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(191, 191, 191)
                                                .addComponent(lblEmpAdminDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)
                                                .addComponent(txtEmpAdminDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnEmpAdminFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblEmpAdminNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(31, 31, 31)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblEmpAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblEmpAdminApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblEmpAdminApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblEmpAdminFechaNacimiento)
                                                    .addComponent(lblEmpAdminRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtEmpAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmpAdminApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmpAdminApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmpAdminFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtEmpAdminRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(txtEmpAdminNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmpAdminCargo)
                                    .addComponent(lblEmpAdminUsuario))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboEmpAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtEmpAdminUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmpAdminHorario)
                                    .addComponent(lblEmpAdminContraseña))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(comboEmpAdminHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmpAdminContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEmpAdminNuevoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEmpAdminGuardarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEmpAdminModificarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEmpAdminEliminarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEmpAdminCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmpAdminBuscarEmp)
                                .addGap(6, 6, 6)
                                .addComponent(txtEmpAdminBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnEmpAdminBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEmpAdminListarEmpleados))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpAdminHeaderDatosPersonales)
                    .addComponent(lblEmpAdminHeaderListadoPersonal))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpAdmHeaderDatosPersonalesSeparador)
                    .addComponent(lblEmpAdmHeaderListadoPersonalSeparador))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEmpAdminFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(lblEmpAdminNumeroEmpleado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminNombre)
                                .addGap(25, 25, 25)
                                .addComponent(lblEmpAdminApellidoPaterno)
                                .addGap(25, 25, 25)
                                .addComponent(lblEmpAdminApellidoMaterno)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmpAdminFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(lblEmpAdminRFC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmpAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtEmpAdminApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtEmpAdminApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtEmpAdminFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtEmpAdminRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblEmpAdminSexo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(rbtFemenino))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(rbtMasculino)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmpAdminNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminDomicilio))
                            .addComponent(txtEmpAdminDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminTelefono))
                            .addComponent(txtEmpAdminTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminEMail))
                            .addComponent(txtEmpAdminEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblEmpAdminNivelEstudios))
                            .addComponent(txtEmpAdminNivelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(lblEmpAdminHeaderDatosUsuario)
                        .addGap(6, 6, 6)
                        .addComponent(lblEmpAdmHeaderDatosUsuarioSeparador))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblEmpAdminBuscarEmp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtEmpAdminBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnEmpAdminBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpAdminListarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEmpAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(lblEmpAdminUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboEmpAdminCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtEmpAdminUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblEmpAdminHorario)
                        .addGap(20, 20, 20)
                        .addComponent(lblEmpAdminContraseña))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboEmpAdminHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtEmpAdminContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmpAdminGuardarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpAdminNuevoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmpAdminEliminarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpAdminModificarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpAdminCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEmpAdminBuscarEmp;
    public javax.swing.JButton btnEmpAdminCancelar;
    public javax.swing.JButton btnEmpAdminEliminarEmp;
    public javax.swing.JButton btnEmpAdminFoto;
    public javax.swing.JButton btnEmpAdminGuardarEmp;
    public javax.swing.JButton btnEmpAdminListarEmpleados;
    public javax.swing.JButton btnEmpAdminModificarEmp;
    public javax.swing.JButton btnEmpAdminNuevoEmp;
    public javax.swing.JComboBox comboEmpAdminCargo;
    public javax.swing.JComboBox comboEmpAdminHorario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpAdmHeaderDatosPersonalesSeparador;
    private javax.swing.JLabel lblEmpAdmHeaderDatosUsuarioSeparador;
    private javax.swing.JLabel lblEmpAdmHeaderListadoPersonalSeparador;
    private javax.swing.JLabel lblEmpAdminApellidoMaterno;
    private javax.swing.JLabel lblEmpAdminApellidoPaterno;
    private javax.swing.JLabel lblEmpAdminBuscarEmp;
    private javax.swing.JLabel lblEmpAdminCargo;
    private javax.swing.JLabel lblEmpAdminContraseña;
    private javax.swing.JLabel lblEmpAdminDomicilio;
    private javax.swing.JLabel lblEmpAdminEMail;
    private javax.swing.JLabel lblEmpAdminFechaNacimiento;
    private javax.swing.JLabel lblEmpAdminHeaderDatosPersonales;
    private javax.swing.JLabel lblEmpAdminHeaderDatosUsuario;
    private javax.swing.JLabel lblEmpAdminHeaderListadoPersonal;
    private javax.swing.JLabel lblEmpAdminHorario;
    private javax.swing.JLabel lblEmpAdminNivelEstudios;
    private javax.swing.JLabel lblEmpAdminNombre;
    public javax.swing.JLabel lblEmpAdminNumeroEmpleado;
    private javax.swing.JLabel lblEmpAdminRFC;
    private javax.swing.JLabel lblEmpAdminSexo;
    private javax.swing.JLabel lblEmpAdminTelefono;
    private javax.swing.JLabel lblEmpAdminUsuario;
    public javax.swing.ButtonGroup rbgSexo;
    public javax.swing.JRadioButton rbtFemenino;
    public javax.swing.JRadioButton rbtMasculino;
    public javax.swing.JTable tablaEmpAdminListadoPersonal;
    public javax.swing.JTextField txtEmpAdminApellidoMaterno;
    public javax.swing.JTextField txtEmpAdminApellidoPaterno;
    public javax.swing.JTextField txtEmpAdminBuscarEmp;
    public javax.swing.JPasswordField txtEmpAdminContraseña;
    public javax.swing.JTextField txtEmpAdminDomicilio;
    public javax.swing.JTextField txtEmpAdminEMail;
    public com.toedter.calendar.JDateChooser txtEmpAdminFechaNacimiento;
    public javax.swing.JTextField txtEmpAdminNivelEstudios;
    public javax.swing.JTextField txtEmpAdminNombre;
    public javax.swing.JLabel txtEmpAdminNumeroEmpleado;
    public javax.swing.JTextField txtEmpAdminRFC;
    public javax.swing.JTextField txtEmpAdminTelefono;
    public javax.swing.JTextField txtEmpAdminUsuario;
    // End of variables declaration//GEN-END:variables
}
