/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistaSAV;

/**
 *
 * @author GarciHard
 */
public class PanelAvionAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelAvionAdmin
     */
    public PanelAvionAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAvionAdminEliminarAvion = new javax.swing.JButton();
        btnAvionAdminNuevoAvion = new javax.swing.JButton();
        btnAvionAdminBuscarAvion = new javax.swing.JButton();
        btnAvionAdminFoto = new javax.swing.JButton();
        btnAvionAdminGuardarAvion = new javax.swing.JButton();
        btnAvionAdminModificarAvion = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        lblEmpAdminBuscarEmp = new javax.swing.JLabel();
        lblEmpAdmHeaderListadoPersonalSeparador = new javax.swing.JLabel();
        lblEmpAdminTelefono = new javax.swing.JLabel();
        lblEmpAdminDomicilio = new javax.swing.JLabel();
        lblEmpAdminSexo = new javax.swing.JLabel();
        lblEmpAdminRFC = new javax.swing.JLabel();
        lblEmpAdminApellidoMaterno = new javax.swing.JLabel();
        lblEmpAdminApellidoPaterno = new javax.swing.JLabel();
        lblEmpAdminHeaderListadoPersonal = new javax.swing.JLabel();
        lblEmpAdminNombre = new javax.swing.JLabel();
        lblEmpAdminHeaderDatosPersonales = new javax.swing.JLabel();
        lblEmpAdmHeaderDatosPersonalesSeparador = new javax.swing.JLabel();
        lblEmpAdminNumeroEmpleado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtEmpAdminBuscarEmp = new javax.swing.JTextField();
        txtEmpAdminNombre = new javax.swing.JTextField();
        txtEmpAdminApellidoPaterno = new javax.swing.JTextField();
        txtEmpAdminNumeroEmpleado = new javax.swing.JTextField();
        txtEmpAdminRFC = new javax.swing.JTextField();
        txtEmpAdminApellidoMaterno = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 100, 133));

        btnAvionAdminEliminarAvion.setBackground(new java.awt.Color(26, 188, 156));
        btnAvionAdminEliminarAvion.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnAvionAdminEliminarAvion.setForeground(new java.awt.Color(255, 255, 255));
        btnAvionAdminEliminarAvion.setText("Eliminar");
        btnAvionAdminEliminarAvion.setBorder(null);
        btnAvionAdminEliminarAvion.setBorderPainted(false);
        btnAvionAdminEliminarAvion.setContentAreaFilled(false);
        btnAvionAdminEliminarAvion.setOpaque(true);

        btnAvionAdminNuevoAvion.setBackground(new java.awt.Color(26, 188, 156));
        btnAvionAdminNuevoAvion.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnAvionAdminNuevoAvion.setForeground(new java.awt.Color(255, 255, 255));
        btnAvionAdminNuevoAvion.setText("Nuevo");
        btnAvionAdminNuevoAvion.setBorder(null);
        btnAvionAdminNuevoAvion.setBorderPainted(false);
        btnAvionAdminNuevoAvion.setContentAreaFilled(false);
        btnAvionAdminNuevoAvion.setOpaque(true);

        btnAvionAdminBuscarAvion.setBackground(new java.awt.Color(26, 188, 156));
        btnAvionAdminBuscarAvion.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnAvionAdminBuscarAvion.setForeground(new java.awt.Color(255, 255, 255));
        btnAvionAdminBuscarAvion.setText("Buscar");
        btnAvionAdminBuscarAvion.setBorder(null);
        btnAvionAdminBuscarAvion.setBorderPainted(false);
        btnAvionAdminBuscarAvion.setContentAreaFilled(false);
        btnAvionAdminBuscarAvion.setOpaque(true);

        btnAvionAdminFoto.setBackground(new java.awt.Color(0, 100, 133));
        btnAvionAdminFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSAV/ImagenNoDisponibleII.png"))); // NOI18N
        btnAvionAdminFoto.setBorderPainted(false);
        btnAvionAdminFoto.setContentAreaFilled(false);
        btnAvionAdminFoto.setOpaque(true);

        btnAvionAdminGuardarAvion.setBackground(new java.awt.Color(26, 188, 156));
        btnAvionAdminGuardarAvion.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnAvionAdminGuardarAvion.setForeground(new java.awt.Color(255, 255, 255));
        btnAvionAdminGuardarAvion.setText("Guardar");
        btnAvionAdminGuardarAvion.setBorder(null);
        btnAvionAdminGuardarAvion.setBorderPainted(false);
        btnAvionAdminGuardarAvion.setContentAreaFilled(false);
        btnAvionAdminGuardarAvion.setOpaque(true);

        btnAvionAdminModificarAvion.setBackground(new java.awt.Color(26, 188, 156));
        btnAvionAdminModificarAvion.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        btnAvionAdminModificarAvion.setForeground(new java.awt.Color(255, 255, 255));
        btnAvionAdminModificarAvion.setText("Modificar");
        btnAvionAdminModificarAvion.setBorder(null);
        btnAvionAdminModificarAvion.setBorderPainted(false);
        btnAvionAdminModificarAvion.setContentAreaFilled(false);
        btnAvionAdminModificarAvion.setOpaque(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblEmpAdminBuscarEmp.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminBuscarEmp.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminBuscarEmp.setText("Buscar");

        lblEmpAdmHeaderListadoPersonalSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderListadoPersonalSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderListadoPersonalSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderListadoPersonalSeparador.setText("____________________________________________________________________________");
        lblEmpAdmHeaderListadoPersonalSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblEmpAdminTelefono.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminTelefono.setText("Caracteristicas");

        lblEmpAdminDomicilio.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminDomicilio.setText("Tipo Estancia");

        lblEmpAdminSexo.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminSexo.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminSexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminSexo.setText("Tipo");

        lblEmpAdminRFC.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminRFC.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminRFC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminRFC.setText("Designador");

        lblEmpAdminApellidoMaterno.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoMaterno.setText("Modelo");

        lblEmpAdminApellidoPaterno.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminApellidoPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminApellidoPaterno.setText("Fabricante");

        lblEmpAdminHeaderListadoPersonal.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderListadoPersonal.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderListadoPersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminHeaderListadoPersonal.setText("Flota Actual");

        lblEmpAdminNombre.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmpAdminNombre.setText("Matricula");

        lblEmpAdminHeaderDatosPersonales.setFont(new java.awt.Font("Heiti SC", 0, 30)); // NOI18N
        lblEmpAdminHeaderDatosPersonales.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminHeaderDatosPersonales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminHeaderDatosPersonales.setText("Datos AeroNave");

        lblEmpAdmHeaderDatosPersonalesSeparador.setFont(new java.awt.Font("Heiti SC", 1, 14)); // NOI18N
        lblEmpAdmHeaderDatosPersonalesSeparador.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdmHeaderDatosPersonalesSeparador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdmHeaderDatosPersonalesSeparador.setText("_____________________________________________________________________________________");
        lblEmpAdmHeaderDatosPersonalesSeparador.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblEmpAdminNumeroEmpleado.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        lblEmpAdminNumeroEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpAdminNumeroEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpAdminNumeroEmpleado.setText("Número de Avión");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        txtEmpAdminNumeroEmpleado.setEditable(false);
        txtEmpAdminNumeroEmpleado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpAdmHeaderDatosPersonalesSeparador)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblEmpAdminHeaderDatosPersonales))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmpAdminNumeroEmpleado)
                                .addComponent(btnAvionAdminFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                            .addComponent(lblEmpAdminNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmpAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpAdminTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmpAdminRFC)
                            .addComponent(txtEmpAdminApellidoPaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmpAdminApellidoMaterno, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmpAdminNombre)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmpAdminHeaderListadoPersonal)
                            .addComponent(lblEmpAdmHeaderListadoPersonalSeparador, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEmpAdminBuscarEmp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmpAdminBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAvionAdminBuscarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAvionAdminEliminarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAvionAdminNuevoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAvionAdminGuardarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAvionAdminModificarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpAdminHeaderDatosPersonales)
                    .addComponent(lblEmpAdminHeaderListadoPersonal))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpAdmHeaderDatosPersonalesSeparador)
                    .addComponent(lblEmpAdmHeaderListadoPersonalSeparador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmpAdminNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmpAdminApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminApellidoPaterno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmpAdminApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminApellidoMaterno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmpAdminRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpAdminRFC))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmpAdminSexo)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmpAdminDomicilio)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmpAdminNumeroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAvionAdminFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmpAdminNumeroEmpleado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblEmpAdminTelefono))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAvionAdminEliminarAvion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmpAdminBuscarEmp)
                                .addComponent(txtEmpAdminBuscarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAvionAdminBuscarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAvionAdminModificarAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvionAdminGuardarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAvionAdminNuevoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAvionAdminBuscarAvion;
    public javax.swing.JButton btnAvionAdminEliminarAvion;
    private javax.swing.JButton btnAvionAdminFoto;
    public javax.swing.JButton btnAvionAdminGuardarAvion;
    public javax.swing.JButton btnAvionAdminModificarAvion;
    public javax.swing.JButton btnAvionAdminNuevoAvion;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblEmpAdmHeaderDatosPersonalesSeparador;
    private javax.swing.JLabel lblEmpAdmHeaderListadoPersonalSeparador;
    private javax.swing.JLabel lblEmpAdminApellidoMaterno;
    private javax.swing.JLabel lblEmpAdminApellidoPaterno;
    private javax.swing.JLabel lblEmpAdminBuscarEmp;
    private javax.swing.JLabel lblEmpAdminDomicilio;
    private javax.swing.JLabel lblEmpAdminHeaderDatosPersonales;
    private javax.swing.JLabel lblEmpAdminHeaderListadoPersonal;
    private javax.swing.JLabel lblEmpAdminNombre;
    private javax.swing.JLabel lblEmpAdminNumeroEmpleado;
    private javax.swing.JLabel lblEmpAdminRFC;
    private javax.swing.JLabel lblEmpAdminSexo;
    private javax.swing.JLabel lblEmpAdminTelefono;
    private javax.swing.JTextField txtEmpAdminApellidoMaterno;
    private javax.swing.JTextField txtEmpAdminApellidoPaterno;
    private javax.swing.JTextField txtEmpAdminBuscarEmp;
    private javax.swing.JTextField txtEmpAdminNombre;
    private javax.swing.JTextField txtEmpAdminNumeroEmpleado;
    private javax.swing.JTextField txtEmpAdminRFC;
    // End of variables declaration//GEN-END:variables
}
